# DO NOT DELETE THIS LINE -- make depend depends on it.

ACJ.o: ACJ.h Complex.h roundoff.h Complex.inline ACJ.inline
Complex.o: Complex.h roundoff.h Complex.inline
Conditions.o: Conditions.h SL2ACJ.h ACJ.h Complex.h roundoff.h Complex.inline
Conditions.o: ACJ.inline
SL2ACJ.o: SL2ACJ.h ACJ.h Complex.h roundoff.h Complex.inline ACJ.inline
